Homework 3 - Data Wrangling/Visualization/Analysis

Option 2: I chose this option to capture data about multiple ETFs across the market to compare data and
performance. I am going to capture data from specifically the S&P 500, Nasdaq, VIX and the Dow. I am sourcing my data from the website called Federal Reserve Economic Data.

In [2]:
#Basic imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import requests 
import bs4
import json
from pathlib import Path

In [4]:
#Setup folders
raw_data_path = "data/raw"
output_path = "output"

In [13]:
#Build a dictionary to feed a function to pull S&P 500, Nasdaq, VIX and the Dow - using the id code
source_data_dict = {"SP500":"S&P 500", "NASDAQCOM":"NASDAQ", "VIXCLS":"VIX", "DJIA":"Dow Jones"}

source_data_dict

{'SP500': 'S&P 500',
 'NASDAQCOM': 'NASDAQ',
 'VIXCLS': 'VIX',
 'DJIA': 'Dow Jones Industrial Average'}

In [6]:
#Configure function to pull based on the dictionary for the ETFs
def pull_source_data(series_id, series_name):
    """ Reading the data series from FRED """
    ##configure url
    url = f"https://fred.stlouisfed.org/graph/fredgraph.csv?id={series_id}"

    ##read the data
    source_df = pd.read_csv(url)

    ##rename the columns for visualization
    source_df = source_df.rename(columns={"observation_date":"date"})
    source_df = source_df.rename(columns={series_id:"value"})

    ##adding the columns 
    source_df["series_id"] = series_id
    source_df["series_name"] = series_name

    return source_df

In [10]:
##Test to view S&P 500 data
SP500_df = pull_source_data("SP500", "S&P 500")

SP500_df.head(10)

         date    value series_id series_name
0  2016-08-19  2183.87     SP500     S&P 500
1  2016-08-22  2182.64     SP500     S&P 500
2  2016-08-23  2186.90     SP500     S&P 500
3  2016-08-24  2175.44     SP500     S&P 500
4  2016-08-25  2172.47     SP500     S&P 500
5  2016-08-26  2169.04     SP500     S&P 500
6  2016-08-29  2180.38     SP500     S&P 500
7  2016-08-30  2176.12     SP500     S&P 500
8  2016-08-31  2170.95     SP500     S&P 500
9  2016-09-01  2170.86     SP500     S&P 500

In [11]:
##Test to view NASDAQ data
NASDAQ_df = pull_source_data("NASDAQCOM", "NASDAQ")

NASDAQ_df.head(10)

         date   value  series_id series_name
0  1971-02-05  100.00  NASDAQCOM      NASDAQ
1  1971-02-08  100.84  NASDAQCOM      NASDAQ
2  1971-02-09  100.76  NASDAQCOM      NASDAQ
3  1971-02-10  100.69  NASDAQCOM      NASDAQ
4  1971-02-11  101.45  NASDAQCOM      NASDAQ
5  1971-02-12  102.05  NASDAQCOM      NASDAQ
6  1971-02-15     NaN  NASDAQCOM      NASDAQ
7  1971-02-16  102.19  NASDAQCOM      NASDAQ
8  1971-02-17  101.74  NASDAQCOM      NASDAQ
9  1971-02-18  101.42  NASDAQCOM      NASDAQ

In [12]:
##Test to view VIX data
VIX_df = pull_source_data("VIXCLS", "VIX")

VIX_df.head(10)

         date  value series_id series_name
0  1990-01-02  17.24    VIXCLS         VIX
1  1990-01-03  18.19    VIXCLS         VIX
2  1990-01-04  19.22    VIXCLS         VIX
3  1990-01-05  20.11    VIXCLS         VIX
4  1990-01-08  20.26    VIXCLS         VIX
5  1990-01-09  22.20    VIXCLS         VIX
6  1990-01-10  22.44    VIXCLS         VIX
7  1990-01-11  20.05    VIXCLS         VIX
8  1990-01-12  24.64    VIXCLS         VIX
9  1990-01-15  26.34    VIXCLS         VIX

In [14]:
##Test to view DJIA data
DJIA_df = pull_source_data("DJIA", "Dow Jones")

DJIA_df.head(10)

         date     value series_id series_name
0  2016-08-19  18552.57      DJIA   Dow Jones
1  2016-08-22  18529.42      DJIA   Dow Jones
2  2016-08-23  18547.30      DJIA   Dow Jones
3  2016-08-24  18481.48      DJIA   Dow Jones
4  2016-08-25  18448.41      DJIA   Dow Jones
5  2016-08-26  18395.40      DJIA   Dow Jones
6  2016-08-29  18502.99      DJIA   Dow Jones
7  2016-08-30  18454.30      DJIA   Dow Jones
8  2016-08-31  18400.88      DJIA   Dow Jones
9  2016-09-01  18419.30      DJIA   Dow Jones

After pulling the Data from FRED on SP500, NASDAW, VIX, and Dow Jones and testing the data pulls, I will be adding all the data to one data frame to create visualizations in the future.

In [20]:
#Creating df to store data from all 4 ETFs

##Configure empty list variable
tot_source_data_list = []

##Looping through each of the source data pulls in the dictionary
for series_id, series_name in source_data_dict.items():
    ##Pulling data source
    single_source_df = pull_source_data(series_id, series_name)

    ##Add it to the list
    tot_source_data_list.append(single_source_df)

##Combine everything 
tot_market_df = pd.concat(tot_source_data_list, ignore_index=True)

##Review the results top
tot_market_df.head(10)

         date    value series_id series_name
0  2016-08-19  2183.87     SP500     S&P 500
1  2016-08-22  2182.64     SP500     S&P 500
2  2016-08-23  2186.90     SP500     S&P 500
3  2016-08-24  2175.44     SP500     S&P 500
4  2016-08-25  2172.47     SP500     S&P 500
5  2016-08-26  2169.04     SP500     S&P 500
6  2016-08-29  2180.38     SP500     S&P 500
7  2016-08-30  2176.12     SP500     S&P 500
8  2016-08-31  2170.95     SP500     S&P 500
9  2016-09-01  2170.86     SP500     S&P 500

In [19]:
##Review the results bottom
tot_market_df.tail(10)

             date     value series_id                   series_name
29248  2026-08-05  54349.12      DJIA  Dow Jones Industrial Average
29249  2026-08-06  53885.10      DJIA  Dow Jones Industrial Average
29250  2026-08-07  54036.93      DJIA  Dow Jones Industrial Average
29251  2026-08-10  53975.98      DJIA  Dow Jones Industrial Average
29252  2026-08-11  53791.85      DJIA  Dow Jones Industrial Average
29253  2026-08-12  53770.27      DJIA  Dow Jones Industrial Average
29254  2026-08-13  53839.99      DJIA  Dow Jones Industrial Average
29255  2026-08-14  53732.41      DJIA  Dow Jones Industrial Average
29256  2026-08-17  53459.78      DJIA  Dow Jones Industrial Average
29257  2026-08-18  53343.40      DJIA  Dow Jones Industrial Average

In [21]:
##Review check results for each ETF
tot_market_df["series_name"].value_counts()

series_name
NASDAQ                          14487
VIX                              9555
S&P 500                          2608
Dow Jones Industrial Average     2608
Name: count, dtype: int64

After reviewing the data a little bit I decided I need to get the same time intervals for each of the stocks to make meaningful comparisons for the visualization presented later on

In [27]:
##Creating a new df of recent data from the same time periods
tot_market_data_comparison_df = tot_market_df[tot_market_df["date"] >= "2017-01-01"].copy()

tot_market_data_comparison_df.head(50)

           date    value series_id series_name
96   2017-01-02      NaN     SP500     S&P 500
97   2017-01-03  2257.83     SP500     S&P 500
98   2017-01-04  2270.75     SP500     S&P 500
99   2017-01-05  2269.00     SP500     S&P 500
100  2017-01-06  2276.98     SP500     S&P 500
101  2017-01-09  2268.90     SP500     S&P 500
102  2017-01-10  2268.90     SP500     S&P 500
103  2017-01-11  2275.32     SP500     S&P 500
104  2017-01-12  2270.44     SP500     S&P 500
105  2017-01-13  2274.64     SP500     S&P 500
106  2017-01-16      NaN     SP500     S&P 500
107  2017-01-17  2267.89     SP500     S&P 500
108  2017-01-18  2271.89     SP500     S&P 500
109  2017-01-19  2263.69     SP500     S&P 500
110  2017-01-20  2271.31     SP500     S&P 500
111  2017-01-23  2265.20     SP500     S&P 500
112  2017-01-24  2280.07     SP500     S&P 500
113  2017-01-25  2298.37     SP500     S&P 500
114  2017-01-26  2296.68     SP500     S&P 500
115  2017-01-27  2294.69     SP500     S&P 500
116  2017-01-30  2280.90     SP500     S&P 500
117  2017-01-31  2278.87     SP500     S&P 500
118  2017-02-01  2279.55     SP500     S&P 500
119  2017-02-02  2280.85     SP500     S&P 500
120  2017-02-03  2297.42     SP500     S&P 500
121  2017-02-06  2292.56     SP500     S&P 500
122  2017-02-07  2293.08     SP500     S&P 500
123  2017-02-08  2294.67     SP500     S&P 500
124  2017-02-09  2307.87     SP500     S&P 500
125  2017-02-10  2316.10     SP500     S&P 500
126  2017-02-13  2328.25     SP500     S&P 500
127  2017-02-14  2337.58     SP500     S&P 500
128  2017-02-15  2349.25     SP500     S&P 500
129  2017-02-16  2347.22     SP500     S&P 500
130  2017-02-17  2351.16     SP500     S&P 500
131  2017-02-20      NaN     SP500     S&P 500
132  2017-02-21  2365.38     SP500     S&P 500
133  2017-02-22  2362.82     SP500     S&P 500
134  2017-02-23  2363.81     SP500     S&P 500
135  2017-02-24  2367.34     SP500     S&P 500
136  2017-02-27  2369.75     SP500     S&P 500
137  2017-02-28  2363.64     SP500     S&P 500
138  2017-03-01  2395.96     SP500     S&P 500
139  2017-03-02  2381.92     SP500     S&P 500
140  2017-03-03  2383.12     SP500     S&P 500
141  2017-03-06  2375.31     SP500     S&P 500
142  2017-03-07  2368.39     SP500     S&P 500
143  2017-03-08  2362.98     SP500     S&P 500
144  2017-03-09  2364.87     SP500     S&P 500
145  2017-03-10  2372.60     SP500     S&P 500

In [28]:
tot_market_data_comparison_df["series_name"].value_counts()

series_name
S&P 500                         2512
Dow Jones Industrial Average    2512
NASDAQ                          2511
VIX                             2511
Name: count, dtype: int64

After mulitple iterations I found that the data is has equal interval amounts after 2017 so i will begin with 2017 moving forward